/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <errno.h>

/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#ifndef _WIN32
#include <unistd.h>
#endif

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif


/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 97
#define YY_END_OF_BUFFER 98
static yyconst short int yy_acclist[388] =
    {   0,
       98,   96,   97,   95,   96,   97,   95,   97,   83,   96,
       97,   96,   97,   89,   96,   97,   82,   96,   97,   96,
       97,   77,   96,   97,   78,   96,   97,   87,   96,   97,
       86,   96,   97,   74,   96,   97,   85,   96,   97,   81,
       96,   97,   88,   96,   97,   40,   96,   97,   39,   96,
       97,   75,   96,   97,   71,   96,   97,   90,   96,   97,
       76,   96,   97,   91,   96,   97,   94,   96,   97,   37,
       96,   97,   37,   96,   97,   79,   96,   97,   80,   96,
       97,   92,   96,   97,   37,   96,   97,   37,   96,   97,
       37,   96,   97,   37,   96,   97,   37,   96,   97,   37,

       96,   97,   37,   96,   97,   37,   96,   97,   37,   96,
       97,   37,   96,   97,   37,   96,   97,   37,   96,   97,
       37,   96,   97,   37,   96,   97,   37,   96,   97,   72,
       96,   97,   93,   96,   97,   73,   96,   97,   84,   96,
       97,   95,   70,   48,   56,   73,   65,   57,   54,   62,
       52,   63,   53,   64,   43,    1,    2,   55,   44,   40,
       40,   40,   40,   39,   39,   39,   39,   80,   72,   79,
       61,   67,   69,   68,   60,   37,   58,   37,   37,   37,
       37,   37,   37,   10,   37,   37,   37,   37,   37,   37,
       37,   18,   37,   37,   37,   37,   37,   37,   37,   37,

       37,   37,   37,   37,   37,   59,   66,   48,   41,   49,
       43,    2,   44,   42,   40,   40,   40,   40,   38,   39,
       39,   39,   39,   51,   50,   37,   37,   37,   37,   37,
       37,   37,   37,   37,   37,   37,   16,   37,   37,   37,
       20,   37,   37,   37,   37,   37,   37,   37,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   37,   43,   44,
       42,   40,   38,   38,   38,   39,    3,   37,   37,    5,
       37,    6,   37,   37,   37,   37,   37,   12,   37,   13,
       37,   37,   37,   17,   37,   37,   21,   37,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   37,   37,   37,

       34,   37,   37,   37,   38,   38,   45,   38,   38,    4,
       37,    7,   37,   37,   37,   37,   37,   15,   37,   37,
       37,   37,   37,   25,   37,   37,   37,   37,   37,   37,
       37,   32,   37,   37,   37,   36,   37,   46,   47,   45,
       38,   37,   37,   11,   37,   14,   37,   19,   37,   37,
       37,   24,   37,   26,   37,   27,   37,   28,   37,   29,
       37,   30,   37,   37,   37,   37,   46,   47,   37,    9,
       37,   37,   37,   31,   37,   37,   37,    8,   37,   22,
       37,   23,   37,   33,   37,   35,   37
    } ;

static yyconst short int yy_accept[304] =
    {   0,
        1,    1,    1,    2,    4,    7,    9,   12,   14,   17,
       20,   22,   25,   28,   31,   34,   37,   40,   43,   46,
       49,   52,   55,   58,   61,   64,   67,   70,   73,   76,
       79,   82,   85,   88,   91,   94,   97,  100,  103,  106,
      109,  112,  115,  118,  121,  124,  127,  130,  133,  136,
      139,  142,  143,  144,  144,  145,  145,  146,  147,  148,
      149,  149,  149,  150,  151,  152,  153,  154,  155,  155,
      156,  157,  158,  159,  160,  161,  161,  161,  162,  163,
      163,  164,  165,  166,  167,  168,  169,  170,  171,  172,
      173,  174,  175,  176,  177,  177,  177,  178,  179,  180,

      181,  182,  183,  184,  186,  187,  188,  189,  190,  191,
      192,  194,  195,  196,  197,  198,  199,  200,  201,  202,
      203,  204,  205,  206,  207,  208,  209,  209,  209,  209,
      209,  210,  210,  210,  211,  211,  212,  213,  213,  214,
      214,  215,  216,  217,  218,  219,  219,  220,  221,  222,
      223,  224,  225,  226,  227,  228,  229,  230,  231,  232,
      233,  234,  235,  236,  237,  239,  240,  241,  243,  244,
      245,  246,  247,  248,  249,  250,  251,  252,  253,  254,
      255,  256,  257,  258,  259,  259,  259,  259,  259,  259,
      260,  260,  261,  262,  263,  263,  263,  264,  264,  265,

      266,  267,  269,  270,  272,  274,  275,  276,  277,  278,
      280,  282,  283,  284,  286,  287,  289,  290,  291,  292,
      293,  294,  295,  296,  297,  298,  299,  300,  301,  303,
      304,  305,  305,  305,  305,  305,  305,  305,  306,  307,
      307,  308,  309,  310,  312,  314,  315,  316,  317,  318,
      320,  321,  322,  323,  324,  326,  327,  328,  329,  330,
      331,  332,  334,  335,  336,  338,  338,  339,  339,  340,
      341,  342,  343,  344,  346,  348,  350,  351,  352,  354,
      356,  358,  360,  362,  364,  365,  366,  367,  368,  369,
      370,  372,  373,  374,  376,  377,  378,  380,  382,  384,

      386,  388,  388
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   18,
       18,   18,   18,   18,   18,   19,   20,   21,   22,   23,
       24,   25,   26,    1,   27,   27,   27,   27,   28,   29,
       30,   30,   30,   30,   30,   31,   30,   30,   30,   32,
       30,   30,   30,   30,   33,   30,   30,   34,   30,   30,
       35,   36,   37,   38,   30,    1,   39,   40,   41,   42,

       43,   44,   45,   46,   47,   30,   48,   49,   50,   51,
       52,   53,   30,   54,   55,   56,   57,   58,   59,   60,
       61,   62,   63,   64,   65,   66,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[67] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    4,    1,    1,
        1,    1,    1,    1,    5,    1,    6,    6,    7,    7,
        1,    1,    1,    1,    1,    3,    7,    7,    7,    8,
        8,    8,    8,    8,    1,    3,    1,    1,    6,    6,
        7,    7,    7,    6,    8,    8,    8,    8,    8,    8,
        9,    8,    8,    9,    8,    9,    8,    9,    8,    9,
        8,    8,    1,    1,    1,    1
    } ;

static yyconst short int yy_base[313] =
    {   0,
        0,    0,  582,  583,   65,   67,  557,   66,   48,   67,
      544,  583,  583,  555,   63,  583,   64,   62,   74,   88,
      134,  553,  583,   88,  553,   59,  583,    0,   87,  583,
      583,  552,  518,  520,   47,   58,   64,   48,  521,   74,
      520,  528,   80,  509,  109,  517,  522,  583,   80,  583,
      583,  127,  583,  127,  138,  116,  583,  583,  583,  583,
      130,  129,  583,  583,  583,  583,  583,  583,  552,  179,
      583,    0,  583,  212,  101,  196,  161,  125,  119,  551,
      137,    0,  169,  141,  152,  583,  583,  583,  541,  583,
      583,  583,  540,    0,  152,  527,  583,  506,  518,  505,

      520,  507,  513,  499,  500,  497,  497,  500,  497,  494,
        0,  156,  498,  148,  480,   97,  167,  482,  475,  521,
      137,  170,  475,  583,  583,  231,  516,  230,  233,    0,
      583,  229,    0,  583,  240,  583,    0,  254,  583,  258,
      262,   63,  583,  488,  458,    0,  252,  185,  583,  474,
      447,  583,  583,  441,  453,  448,  436,  189,  449,  447,
      443,  435,  441,  444,    0,  430,  434,    0,  435,  432,
      422,  420,  421,  422,  429,  415,  413,  413,  425,  415,
      413,  417,  418,  407,  281,  313,  279,  350,  302,  317,
      306,  354,  583,  583,  195,  257,  259,  387,  263,  294,

      583,    0,  407,    0,    0,  398,  405,  394,  401,    0,
        0,  395,  391,    0,  394,    0,  384,  367,  366,  362,
      369,  359,  362,  361,  359,  355,  345,  350,    0,  332,
      344,  302,    0,  217,    0,  396,  405,  271,  583,  345,
      409,  353,  333,    0,    0,  330,  331,  333,  324,    0,
      317,  303,  303,  296,    0,  303,  300,  298,  273,  268,
      270,    0,  257,  256,    0,  413,  417,  424,  445,  583,
      583,  245,  244,    0,    0,    0,  252,  229,    0,    0,
        0,    0,    0,    0,  219,  177,  138,  583,  583,  131,
        0,  110,   99,    0,   81,   33,    0,    0,    0,    0,

        0,  583,  494,  503,  507,  514,  521,  530,  535,  537,
      539,  541
    } ;

static yyconst short int yy_def[313] =
    {   0,
      302,    1,  302,  302,  302,  302,  302,  303,  302,  302,
      304,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  305,  305,  302,
      302,  302,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  302,  302,  302,
      302,  302,  302,  303,  302,  306,  302,  302,  302,  302,
      304,  307,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  308,  302,  302,   20,  302,  302,  302,  302,  309,
      302,   21,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  305,  303,  304,  302,  305,  305,  305,

      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  302,  302,  302,  302,  302,  303,  310,
      302,  304,  311,  302,  302,  302,  308,  302,  302,  302,
      302,  302,  302,  302,  302,  312,  309,  302,  302,  302,
      302,  302,  302,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  303,  303,  304,  304,  302,  302,
      302,  302,  302,  302,  312,  312,  302,  302,  302,  302,

      302,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  303,  186,  304,  188,  302,  302,  302,  302,  302,
      302,  302,  302,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  302,  302,  302,  302,  302,
      302,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  302,  302,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,

      305,    0,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302
    } ;

static yyconst short int yy_nxt[650] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   21,   21,
       22,   23,   24,   25,   26,   27,   28,   28,   28,   28,
       29,   28,   29,   28,   30,    4,   31,   32,   33,   34,
       35,   36,   37,   38,   39,   28,   40,   28,   41,   28,
       28,   28,   28,   42,   43,   44,   45,   46,   47,   28,
       28,   28,   48,   49,   50,   51,   52,   52,   52,   52,
       55,   57,   58,   59,   64,  301,   69,   66,   70,   70,
       70,   70,   92,   93,   71,  100,   65,   67,   68,   72,
       60,   95,  101,   87,   96,  143,  108,   73,  102,  109,

      103,   56,   74,  124,   75,   75,   76,   76,   88,  104,
       89,   90,  105,   95,  106,   77,   96,  111,   78,  143,
       79,   80,  300,  107,  112,  115,  116,  120,   52,   52,
       77,   55,  129,  129,  302,  117,   81,  131,  118,  126,
      126,  174,   95,  125,   79,  132,  132,   80,   74,  144,
       82,   82,   82,   82,  299,  142,   55,  143,  175,  121,
      302,   77,   56,  298,   83,   62,   84,  145,  127,  143,
      127,  150,  140,  297,  140,  130,   77,  141,  141,  141,
      141,  143,   85,  180,  149,  142,  296,   56,  133,  151,
       84,  181,  170,  143,  128,   70,   70,   70,   70,  148,

      148,  149,  171,  172,  167,  176,  135,  136,  149,  136,
       74,  168,   76,   76,   76,   76,  182,  149,  183,  295,
      177,  135,  136,   77,  131,  149,  236,  136,   70,   70,
       70,   70,  126,  126,   95,   95,  131,   55,   77,  138,
      139,  149,  139,  206,  207,  187,  187,  236,  127,  185,
      185,  189,   62,  189,  138,  139,  190,  190,  190,  190,
      139,  127,  294,  127,   62,  191,  196,  191,   56,  293,
      192,  192,  192,  192,  141,  141,  141,  141,  141,  141,
      141,  141,  197,  198,  199,   55,  131,  128,  237,  238,
      193,  239,  193,  242,  292,  234,  234,  232,  232,  291,

      200,  290,  287,  239,  198,  193,   55,  286,  199,  237,
      193,  243,  285,  284,   62,  239,   56,   55,  190,  190,
      190,  190,  192,  192,  192,  192,  239,  239,  283,  233,
      233,  233,  233,  190,  190,  190,  190,   56,  282,  233,
      233,  233,  238,  281,  280,  136,  279,  136,   56,  278,
      239,  233,  233,  233,  233,  233,  233,  131,  277,  276,
      136,  241,  241,  241,  241,  136,  235,  235,  235,  235,
      192,  192,  192,  192,  275,  274,  235,  235,  235,  273,
      272,  271,  139,  271,  139,   62,  265,  264,  235,  235,
      235,  235,  235,  235,  263,  262,  261,  139,  240,  260,

      240,  259,  139,  241,  241,  241,  241,  266,  258,  266,
      257,  256,  267,  267,  267,  267,  268,  255,  268,  254,
      253,  269,  269,  269,  269,  241,  241,  241,  241,  267,
      267,  267,  267,  267,  267,  267,  267,  270,  252,  270,
      269,  269,  269,  269,  251,  288,  250,  288,  249,  248,
      247,  246,  270,  245,  244,  231,  230,  270,  229,  228,
      288,  269,  269,  269,  269,  288,  227,  226,  225,  224,
      223,  222,  221,  289,  220,  289,  219,  218,  217,  216,
      215,  214,  213,  212,  211,  210,  209,  208,  289,  205,
      204,  203,  202,  289,   54,  201,   54,   54,   54,   54,

       54,   54,   54,   61,  201,   61,  194,   61,   61,   61,
       61,   61,   94,   94,   94,   94,   54,   54,  194,   54,
       95,  184,   54,   61,   61,   95,   61,  179,  178,   61,
      137,  173,  137,  137,  137,  137,  137,  137,  137,  147,
      147,  147,  186,  186,  188,  188,  195,  195,  169,  166,
      165,  164,  163,  162,  161,  160,  159,  158,  157,  156,
      155,  154,   62,  153,  152,  146,  134,  123,  122,  119,
      114,  113,  110,   99,   98,   97,   91,   86,   63,   62,
       53,  302,    3,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,

      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302
    } ;

static yyconst short int yy_chk[650] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    5,    5,    6,    6,
        8,    9,    9,   10,   15,  296,   18,   17,   18,   18,
       18,   18,   26,   26,   19,   35,   15,   17,   17,   19,
       10,   29,   35,   24,   29,  142,   38,   19,   35,   38,

       36,    8,   20,   49,   20,   20,   20,   20,   24,   36,
       24,   24,   37,   45,   37,   20,   45,   40,   20,  142,
       20,   20,  295,   37,   40,   43,   43,   45,   52,   52,
       20,   54,   56,   56,   75,   43,   20,   61,   43,   55,
       55,  116,   55,   49,   20,   62,   62,   20,   21,   79,
       21,   21,   21,   21,  293,   78,   95,   78,  116,   45,
       75,   21,   54,  292,   21,   61,   21,   79,   55,   81,
       55,   84,   77,  290,   77,   56,   21,   77,   77,   77,
       77,   78,   21,  121,   85,   81,  287,   95,   62,   84,
       21,  121,  114,   81,   55,   70,   70,   70,   70,   83,

       85,   83,  114,  114,  112,  117,   70,   70,   85,   70,
       76,  112,   76,   76,   76,   76,  122,  148,  122,  286,
      117,   70,   70,   76,  234,   83,  195,   70,   74,   74,
       74,   74,  126,  126,  128,  126,  132,  129,   76,   74,
       74,  148,   74,  158,  158,  132,  132,  195,  128,  129,
      129,  135,  234,  135,   74,   74,  135,  135,  135,  135,
       74,  126,  285,  126,  132,  138,  147,  138,  129,  278,
      138,  138,  138,  138,  140,  140,  140,  140,  141,  141,
      141,  141,  147,  147,  147,  185,  187,  126,  196,  197,
      141,  197,  141,  199,  277,  187,  187,  185,  185,  273,

      147,  272,  264,  238,  147,  141,  232,  263,  147,  196,
      141,  199,  261,  260,  187,  197,  185,  186,  189,  189,
      189,  189,  191,  191,  191,  191,  200,  238,  259,  186,
      186,  186,  186,  190,  190,  190,  190,  232,  258,  186,
      186,  186,  200,  257,  256,  190,  254,  190,  186,  253,
      200,  186,  186,  186,  186,  186,  186,  188,  252,  251,
      190,  240,  240,  240,  240,  190,  188,  188,  188,  188,
      192,  192,  192,  192,  249,  248,  188,  188,  188,  247,
      246,  243,  192,  242,  192,  188,  231,  230,  188,  188,
      188,  188,  188,  188,  228,  227,  226,  192,  198,  225,

      198,  224,  192,  198,  198,  198,  198,  236,  223,  236,
      222,  221,  236,  236,  236,  236,  237,  220,  237,  219,
      218,  237,  237,  237,  237,  241,  241,  241,  241,  266,
      266,  266,  266,  267,  267,  267,  267,  241,  217,  241,
      268,  268,  268,  268,  215,  267,  213,  267,  212,  209,
      208,  207,  241,  206,  203,  184,  183,  241,  182,  181,
      267,  269,  269,  269,  269,  267,  180,  179,  178,  177,
      176,  175,  174,  269,  173,  269,  172,  171,  170,  169,
      167,  166,  164,  163,  162,  161,  160,  159,  269,  157,
      156,  155,  154,  269,  303,  151,  303,  303,  303,  303,

      303,  303,  303,  304,  150,  304,  145,  304,  304,  304,
      304,  304,  305,  305,  305,  305,  306,  306,  144,  306,
      127,  123,  306,  307,  307,  120,  307,  119,  118,  307,
      308,  115,  308,  308,  308,  308,  308,  308,  308,  309,
      309,  309,  310,  310,  311,  311,  312,  312,  113,  110,
      109,  108,  107,  106,  105,  104,  103,  102,  101,  100,
       99,   98,   96,   93,   89,   80,   69,   47,   46,   44,
       42,   41,   39,   34,   33,   32,   25,   22,   14,   11,
        7,    3,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,

      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "Grammar.lex"
#define INITIAL 0
/*
(This Lex file is accompanied by a matching Yacc file.)
In 1985, Jeff Lee published his Yacc grammar based on a draft version of the ANSI C standard, along with a supporting Lex specification. Tom Stockfisch reposted those files to net.sources in 1987; as mentioned in the answer to question 17.25 of the comp.lang.c FAQ, they used to be available from ftp.uu.net as usenet/net.sources/ansi.c.grammar.Z.

The version you see here has been updated based on the 2011 ISO C standard. (The previous version's Lex and Yacc files for ANSI C9X still exist as archived copies.)

It is assumed that translation phases 1..5 have already been completed, including preprocessing and _Pragma processing. The Lex rule for string literals will perform concatenation (translation phase 6). Transliteration of universal character names (\uHHHH or \UHHHHHHHH) must have been done by either the preprocessor or a replacement for the input() macro used by Lex (or the YY_INPUT function used by Flex) to read characters. Although comments should have been changed to space characters during translation phase 3, there are Lex rules for them anyway.

I want to keep this version as close to the current C Standard grammar as possible; please let me know if you discover discrepancies.
(There is an FAQ for this grammar that you might want to read first.)

jutta@pobox.com, 2012

Last edit: 2012-12-19 DAGwyn@aol.com

Note: The following %-parameters are the minimum sizes needed for real Lex.
%e	number of parsed tree nodes
%p	number of positions
%n	number of states
%k	number of packed character classes
%a	number of transitions
%o	size of output array
*/
#line 27 "Grammar.lex"
#include "../AST/AbstractSyntaxTree.h"
#include <cstdio>
#include <iostream>
#include "y.tab.h"

extern void yyerror(const char *);  /* prints grammar violation message */

//extern int sym_type(const char *);  /* returns type from symbol table */

#define sym_type(identifier) IDENTIFIER /* with no symbol table, fake it */

static void comment(void);
static int check_type(void);
static void count(void);

int column = 0;
#line 706 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 67 "Grammar.lex"

#line 870 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 303 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 583 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 68 "Grammar.lex"
{ comment(); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 69 "Grammar.lex"
{ /* consume //-comment */ }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 71 "Grammar.lex"
{ count(); yylval.ast = createTree("AUTO", 0, yylineno); return(AUTO); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 72 "Grammar.lex"
{ count(); yylval.ast = createTree("BREAK", 0, yylineno); return(BREAK); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 73 "Grammar.lex"
{ count(); yylval.ast = createTree("CASE", 0, yylineno); return(CASE); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 74 "Grammar.lex"
{ count(); yylval.ast = createTree("CHAR", 0, yylineno); return(CHAR); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 75 "Grammar.lex"
{ count(); yylval.ast = createTree("CONST", 0, yylineno); return(CONST); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 76 "Grammar.lex"
{ count(); yylval.ast = createTree("CONTINUE", 0, yylineno); return(CONTINUE); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 77 "Grammar.lex"
{ count(); yylval.ast = createTree("DEFAULT", 0, yylineno); return(DEFAULT); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 78 "Grammar.lex"
{ count(); yylval.ast = createTree("DO", 0, yylineno); return(DO); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 79 "Grammar.lex"
{ count(); yylval.ast = createTree("DOUBLE", 0, yylineno); return(DOUBLE); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 80 "Grammar.lex"
{ count(); yylval.ast = createTree("ELSE", 0, yylineno); return(ELSE); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 81 "Grammar.lex"
{ count(); yylval.ast = createTree("ENUM", 0, yylineno); return(ENUM); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 82 "Grammar.lex"
{ count(); yylval.ast = createTree("EXTERN", 0, yylineno); return(EXTERN); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 83 "Grammar.lex"
{ count(); yylval.ast = createTree("FLOAT", 0, yylineno); return(FLOAT); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 84 "Grammar.lex"
{ count(); yylval.ast = createTree("FOR", 0, yylineno); return(FOR); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 85 "Grammar.lex"
{ count(); yylval.ast = createTree("GOTO", 0, yylineno); return(GOTO); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 86 "Grammar.lex"
{ count(); yylval.ast = createTree("IF", 0, yylineno); return(IF); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 87 "Grammar.lex"
{ count(); yylval.ast = createTree("INLINE", 0, yylineno); return(INLINE); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 88 "Grammar.lex"
{ count(); yylval.ast = createTree("INT", 0, yylineno); return(INT); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 89 "Grammar.lex"
{ count(); yylval.ast = createTree("LONG", 0, yylineno); return(LONG); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 90 "Grammar.lex"
{ count(); yylval.ast = createTree("REGISTER", 0, yylineno); return(REGISTER); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 91 "Grammar.lex"
{ count(); yylval.ast = createTree("RESTRICT", 0, yylineno); return(RESTRICT); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 92 "Grammar.lex"
{ count(); yylval.ast = createTree("RETURN", 0, yylineno); return(RETURN); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 93 "Grammar.lex"
{ count(); yylval.ast = createTree("SHORT", 0, yylineno); return(SHORT); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 94 "Grammar.lex"
{ count(); yylval.ast = createTree("SIGNED", 0, yylineno); return(SIGNED); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 95 "Grammar.lex"
{ count(); yylval.ast = createTree("SIZEOF", 0, yylineno); return(SIZEOF); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 96 "Grammar.lex"
{ count(); yylval.ast = createTree("STATIC", 0, yylineno); return(STATIC); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 97 "Grammar.lex"
{ count(); yylval.ast = createTree("STRUCT", 0, yylineno); return(STRUCT); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 98 "Grammar.lex"
{ count(); yylval.ast = createTree("SWITCH", 0, yylineno); return(SWITCH); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 99 "Grammar.lex"
{ count(); yylval.ast = createTree("TYPEDEF", 0, yylineno); return(TYPEDEF); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 100 "Grammar.lex"
{ count(); yylval.ast = createTree("UNION", 0, yylineno); return(UNION); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 101 "Grammar.lex"
{ count(); yylval.ast = createTree("UNSIGNED", 0, yylineno); return(UNSIGNED); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 102 "Grammar.lex"
{ count(); yylval.ast = createTree("VOID", 0, yylineno); return(VOID); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 103 "Grammar.lex"
{ count(); yylval.ast = createTree("VOLATILE", 0, yylineno); return(VOLATILE); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 104 "Grammar.lex"
{ count(); yylval.ast = createTree("WHILE", 0, yylineno); return(WHILE); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 107 "Grammar.lex"
{ count(); yylval.ast = createTree("IDENTIFIER", 0, yylineno); return check_type(); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 109 "Grammar.lex"
{ count(); yylval.ast = createTree("I_CONSTANT", 0, yylineno); return I_CONSTANT; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 110 "Grammar.lex"
{ count(); yylval.ast = createTree("I_CONSTANT", 0, yylineno); return I_CONSTANT; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 111 "Grammar.lex"
{ count(); yylval.ast = createTree("I_CONSTANT", 0, yylineno); return I_CONSTANT; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 112 "Grammar.lex"
{ count(); yylval.ast = createTree("C_CONSTANT", 0, yylineno); return C_CONSTANT; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 114 "Grammar.lex"
{ count(); yylval.ast = createTree("F_CONSTANT", 0, yylineno); return F_CONSTANT; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 115 "Grammar.lex"
{ count(); yylval.ast = createTree("F_CONSTANT", 0, yylineno); return F_CONSTANT; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 116 "Grammar.lex"
{ count(); yylval.ast = createTree("F_CONSTANT", 0, yylineno); return F_CONSTANT; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 117 "Grammar.lex"
{ count(); yylval.ast = createTree("F_CONSTANT", 0, yylineno); return F_CONSTANT; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 118 "Grammar.lex"
{ count(); yylval.ast = createTree("F_CONSTANT", 0, yylineno); return F_CONSTANT; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 119 "Grammar.lex"
{ count(); yylval.ast = createTree("F_CONSTANT", 0, yylineno); return F_CONSTANT; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 121 "Grammar.lex"
{ count(); yylval.ast = createTree("STRING_LITERAL", 0, yylineno); return STRING_LITERAL; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 123 "Grammar.lex"
{ return ELLIPSIS; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 124 "Grammar.lex"
{ count(); yylval.ast = createTree("RIGHT_ASSIGN", 0, yylineno); return RIGHT_ASSIGN; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 125 "Grammar.lex"
{ count(); yylval.ast = createTree("LEFT_ASSIGN", 0, yylineno); return LEFT_ASSIGN; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 126 "Grammar.lex"
{ count(); yylval.ast = createTree("ADD_ASSIGN", 0, yylineno); return ADD_ASSIGN; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 127 "Grammar.lex"
{ count(); yylval.ast = createTree("SUB_ASSIGN", 0, yylineno); return SUB_ASSIGN; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 128 "Grammar.lex"
{ count(); yylval.ast = createTree("MUL_ASSIGN", 0, yylineno); return MUL_ASSIGN; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 129 "Grammar.lex"
{ count(); yylval.ast = createTree("DIV_ASSIGN", 0, yylineno); return DIV_ASSIGN; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 130 "Grammar.lex"
{ count(); yylval.ast = createTree("MOD_ASSIGN", 0, yylineno); return MOD_ASSIGN; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 131 "Grammar.lex"
{ count(); yylval.ast = createTree("AND_ASSIGN", 0, yylineno); return AND_ASSIGN; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 132 "Grammar.lex"
{ count(); yylval.ast = createTree("XOR_ASSIGN", 0, yylineno); return XOR_ASSIGN; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 133 "Grammar.lex"
{ count(); yylval.ast = createTree("OR_ASSIGN", 0, yylineno); return OR_ASSIGN; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 134 "Grammar.lex"
{ count(); yylval.ast = createTree("RIGHT_OP", 0, yylineno); return RIGHT_OP; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 135 "Grammar.lex"
{ count(); yylval.ast = createTree("LEFT_OP", 0, yylineno); return LEFT_OP; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 136 "Grammar.lex"
{ count(); yylval.ast = createTree("INC_OP", 0, yylineno); return INC_OP; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 137 "Grammar.lex"
{ count(); yylval.ast = createTree("DEC_OP", 0, yylineno); return DEC_OP; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 138 "Grammar.lex"
{ count(); yylval.ast = createTree("PTR_OP", 0, yylineno); return PTR_OP; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 139 "Grammar.lex"
{ count(); yylval.ast = createTree("AND_OP", 0, yylineno); return AND_OP; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 140 "Grammar.lex"
{ count(); yylval.ast = createTree("OR_OP", 0, yylineno); return OR_OP; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 141 "Grammar.lex"
{ count(); yylval.ast = createTree("LE_OP", 0, yylineno); return LE_OP; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 142 "Grammar.lex"
{ count(); yylval.ast = createTree("GE_OP", 0, yylineno); return GE_OP; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 143 "Grammar.lex"
{ count(); yylval.ast = createTree("EQ_OP", 0, yylineno); return EQ_OP; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 144 "Grammar.lex"
{ count(); yylval.ast = createTree("NE_OP", 0, yylineno); return NE_OP; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 145 "Grammar.lex"
{ count(); yylval.ast = createTree(";", 0, yylineno); return ';'; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 146 "Grammar.lex"
{ count(); yylval.ast = createTree("{", 0, yylineno); return '{'; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 147 "Grammar.lex"
{ count(); yylval.ast = createTree("}", 0, yylineno); return '}'; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 148 "Grammar.lex"
{ count(); yylval.ast = createTree(",", 0, yylineno); return ','; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 149 "Grammar.lex"
{ count(); yylval.ast = createTree(":", 0, yylineno); return ':'; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 150 "Grammar.lex"
{ count(); yylval.ast = createTree("=", 0, yylineno); return '='; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 151 "Grammar.lex"
{ count(); yylval.ast = createTree("(", 0, yylineno); return '('; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 152 "Grammar.lex"
{ count(); yylval.ast = createTree(")", 0, yylineno); return ')'; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 153 "Grammar.lex"
{ count(); yylval.ast = createTree("[", 0, yylineno); return '['; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 154 "Grammar.lex"
{ count(); yylval.ast = createTree("]", 0, yylineno); return ']'; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 155 "Grammar.lex"
{ count(); yylval.ast = createTree(".", 0, yylineno); return '.'; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 156 "Grammar.lex"
{ count(); yylval.ast = createTree("&", 0, yylineno); return '&'; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 157 "Grammar.lex"
{ count(); yylval.ast = createTree("!", 0, yylineno); return '!'; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 158 "Grammar.lex"
{ count(); yylval.ast = createTree("~", 0, yylineno); return '~'; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 159 "Grammar.lex"
{ count(); yylval.ast = createTree("-", 0, yylineno); return '-'; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 160 "Grammar.lex"
{ count(); yylval.ast = createTree("+", 0, yylineno); return '+'; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 161 "Grammar.lex"
{ count(); yylval.ast = createTree("*", 0, yylineno); return '*'; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 162 "Grammar.lex"
{ count(); yylval.ast = createTree("/", 0, yylineno); return '/'; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 163 "Grammar.lex"
{ count(); yylval.ast = createTree("%", 0, yylineno); return '%'; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 164 "Grammar.lex"
{ count(); yylval.ast = createTree("<", 0, yylineno); return '<'; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 165 "Grammar.lex"
{ count(); yylval.ast = createTree(">", 0, yylineno); return '>'; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 166 "Grammar.lex"
{ count(); yylval.ast = createTree("^", 0, yylineno); return '^'; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 167 "Grammar.lex"
{ count(); yylval.ast = createTree("|", 0, yylineno); return '|'; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 168 "Grammar.lex"
{ count(); yylval.ast = createTree("?", 0, yylineno); return '?'; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 170 "Grammar.lex"
{ /* whitespace separates tokens */ }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 171 "Grammar.lex"
{ /* discard bad characters */ }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 173 "Grammar.lex"
ECHO;
	YY_BREAK
#line 1446 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 303 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 303 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 302);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef _WIN32
#include <unistd.h>
#else
#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 173 "Grammar.lex"


int yywrap(void)        /* called at end of input */
{
    return 1;           /* terminate now */
}

static void comment() {
	column = 0;
	char c, prev = 0;

	while (std::cin >> c)      /* (EOF maps to 0) */
	{
		if (c == '/' && prev == '*')
			return;
		prev = c;
	}
	printf("unterminated comment");
}

void count(void)
{
	int i;

	for (i = 0; yytext[i] != '\0'; i++)
		if (yytext[i] == '\n')
			column = 0;
		else if (yytext[i] == '\t')
			column += 4 - (column % 4);
		else
			column++;
	ECHO;
}
static int check_type(void)
{
    switch (sym_type(yytext))
    {
    case TYPEDEF_NAME:                /* previously defined */
        return TYPEDEF_NAME;
    case ENUMERATION_CONSTANT:        /* previously defined */
        return ENUMERATION_CONSTANT;
    default:                          /* includes undefined */
        return IDENTIFIER;
    }
}